bind:
  addr: localhost
  port: 3210
http:
  max-clients: 800
  req-timeout: 120
  tcp-backlog: 1024
  x-forwarded: true
security:
  cookie-secret: null
  cookie-expiry: 30
internal:
  hostname: null
  protocol: null
dns:
  nameservers:
    - 8.8.8.8
    - 8.8.4.4
couchdb:
  url: http://localhost:5984/v6wos/
