bind:
  addr: localhost
  port: 4000
http:
  max-clients: 800
  req-timeout: 120
  tcp-backlog: 1024
  x-forwarded: true
security:
  cookie-secret: null
  cookie-expiry: 30
internal:
  hostname: null
couchdb:
  url: http://localhost:5984/v6wos/
